=== Luke460/gv-script-tester/scriptTester/properties.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT buffer (propertyList)>
<!ATTLIST buffer
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>

<!ELEMENT propertyList (property)*>
<!ATTLIST propertyList
  xmlns CDATA #FIXED ''>

<!ELEMENT property (name,value)>
<!ATTLIST property
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
  xmlns CDATA #FIXED ''>

=== Luke460/gv-script-tester/scriptTester/DATA-Properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "properties.dtd">
<buffer name="data">
	<propertyList>
		<property>
			<name>FIRST_NAME</name>
			<value><![CDATA[Gino]]></value>
		</property>
		<property>
			<name>LAST_NAME</name>
			<value><![CDATA[Ginotti]]></value>
		</property>
		<property>
			<name>PRIVATE_CAR_PLATE</name>
			<value><![CDATA[AD123CD]]></value>
		</property>
	</propertyList>
</buffer>
